name: ➕ Add stream
description: Request to add a new stream link into the playlist
title: 'Add: '
labels: ['streams:add']

body:
  - type: input
    id: stream_id
    attributes:
      label: Stream ID (required)
      description: "Station ID"
      placeholder: 'BBC AMERICA East'
    validations:
      required: true

  - type: input
    id: stream_url
    attributes:
      label: Stream URL (required)
      description: Link to be added to the playlist
      placeholder: 'https://example.com/playlist.m3u8'
    validations:
      required: true

  - type: dropdown
    id: quality
    attributes:
      label: Quality
      description: Maximum video resolution available on the link
      options:
        - 2160p
        - 1280p
        - 1080p
        - 1080i
        - 720p
        - 576p
        - 576i
        - 480p
        - 480i
        - 360p

  - type: dropdown
    id: label
    attributes:
      label: Label
      description: Is there any reason why the broadcast may not work?
      options:
        - 'Not 24/7'
        - 'Geo-blocked'

  - type: input
    id: http_user_agent
    attributes:
      label: HTTP User Agent
      placeholder: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edge/12.246'

  - type: input
    id: http_referrer
    attributes:
      label: HTTP Referrer
      placeholder: 'https://example.com/'

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: 'Anything else we should know about this broadcast?' 
