name: 🚧 Report a stream
description: Report a broken or unstable stream
title: 'Report: '
labels: ['streams:remove']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form as much as you can so we could efficiently process your request. To suggest a new replacement link, use this [form](https://github.com/iptv-org/iptv/issues/new?assignees=&labels=streams:add&projects=&template=1_streams_add.yml&title=Add%3A+).

  - type: textarea
    id: stream_url
    attributes:
      label: Stream URL
      description: List all links in question (one per line)
      placeholder: 'https://lnc-kdfw-fox-aws.tubi.video/index.m3u8'
    validations:
      required: true

  - type: dropdown
    id: reason
    attributes:
      label: What happened to the stream?
      options:
        - Not loading
        - Constantly interrupts/lagging
        - Stuck at a single frame
        - I see visual artifacts
        - Shows looped video
        - No sound
        - Displays a message asking to renew subscription
        - Other (Place info in Notes Section)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      placeholder: 'Anything else we should know?' 
